sudo: required
language: generic

services: 
    - docker

before_install:
    - docker build -t alehti/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true alehti/docker-react npm run test